name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Test
        uses: onichandame/python-test-action@master
        with:
          python-version: '3.11'
          test-command: python -m unittest discover -s 2024 -p "*.test.py"
